name: Android Debug APK (Gradle)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        run: chmod +x android/gradlew

      - name: Print env (debug)
        run: |
          echo "PWD=$(pwd)"
          ls -la
          ls -la android || true
          ls -la android/app || true

      - name: Build debug APK
        working-directory: android
        # We tee logs to files so we can always upload them
        run: |
          ./gradlew --version | tee gradle-version.log
          ./gradlew assembleDebug --stacktrace --no-daemon | tee gradle-build.log

      # Always collect logs/reports, even if the build failed
      - name: Upload Gradle logs & reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs-and-reports
          if-no-files-found: ignore
          path: |
            android/gradle-build.log
            android/gradle-version.log
            android/**/build/reports/**
            android/**/build/test-results/**
            **/hs_err_pid*.log

      # Only upload APK if we actually built it
      - name: Upload debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
