name: Android Debug APK (Gradle)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Make Gradle wrapper executable
        run: chmod +x android/gradlew

      - name: Print versions
        working-directory: android
        run: |
          ./gradlew -v
          ./gradlew --version

      - name: Build APK (debug) with logs
        working-directory: android
        env:
          GRADLE_OPTS: "-Dorg.gradle.jvmargs='-Xmx3g -Dfile.encoding=UTF-8'"
          # keep daemon to speed up, but enable detailed logs
        run: |
          set -e
          ./gradlew clean :app:assembleDebug \
            --stacktrace --info --warning-mode all | tee gradle-build.log
          echo "Problems report (if generated):"
          ls -R build/reports || true
          mkdir -p build/outputs/ci
          cp -f gradle-build.log build/outputs/ci/ || true

      - name: Upload logs & reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs-and-reports
          path: |
            android/gradle-build.log
            android/build/reports/**
            android/app/build/reports/**
            android/app/build/outputs/logs/**
          if-no-files-found: warn
          compression-level: 6

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
          compression-level: 6
